services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_GRAPHQL_ENDPOINT:-http://host.docker.internal:8080/query}
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"